export const mockFigurants = [
  {
    ICC_number: '5218 58868 7536',
    card_id: 'sona-001',
    characterID: '410',
    character_name: 'Yusuf Miro',
    douane_disposition: 'ACCESS GRANTED',
    faction: 'sona',
    figu_accountID: '719',
    figu_name: 'Roos Schultheiss',
    homeplanet: 'Ghara',
    ic_birthday: '15-7-220NT',
    plotname: 'Dockside witness',
    rank: 'Envoy',
    status: 'figurant',
    threat_assessment: '1',
    bastion_clearance: '0',
    bloodtype: 'O',
  },
  {
    ICC_number: '8044 11932 0071',
    card_id: 'aquila-017',
    characterID: '411',
    character_name: 'Maia Voss',
    douane_disposition: 'ICC VETTED',
    faction: 'aquila',
    figu_accountID: '720',
    figu_name: 'Sam Dekker',
    homeplanet: 'Bastion',
    ic_birthday: '2-3-214NT',
    plotname: 'Security audit',
    rank: 'Lieutenant',
    status: 'figurant-recurring',
    threat_assessment: '2',
    bastion_clearance: '2',
    bloodtype: 'A',
  },
  {
    ICC_number: '1138 90551 4490',
    card_id: 'dugo-204',
    characterID: '412',
    character_name: 'Rafiq Alon',
    douane_disposition: 'ACCESS PENDING',
    faction: 'dugo',
    figu_accountID: '721',
    figu_name: 'Janne Smit',
    homeplanet: 'Haven-3',
    ic_birthday: '28-11-218NT',
    plotname: 'Smuggled relay',
    rank: 'Broker',
    status: 'figurant',
    threat_assessment: '3',
    bastion_clearance: '1',
    bloodtype: 'B',
  },
  {
    ICC_number: '6772 34019 3008',
    card_id: 'ekanesh-042',
    characterID: '413',
    character_name: 'Asha Neral',
    douane_disposition: 'DETAIN',
    faction: 'ekanesh',
    figu_accountID: '',
    figu_name: '',
    homeplanet: 'Ekan Prime',
    ic_birthday: '9-9-207NT',
    plotname: 'Restricted cargo',
    rank: 'Doctor',
    status: 'figurant-recurring',
    threat_assessment: '4',
    bastion_clearance: '0',
    bloodtype: 'AB',
  },
  {
    ICC_number: '3340 77120 8812',
    card_id: 'pendzal-009',
    characterID: '414',
    character_name: 'Toma Revik',
    douane_disposition: 'ACCESS GRANTED',
    faction: 'pendzal',
    figu_accountID: '722',
    figu_name: 'Mara Visser',
    homeplanet: 'Pendzal Station',
    ic_birthday: '1-1-225NT',
    plotname: 'Guild negotiator with unusually long plot label',
    rank: 'Quartermaster',
    status: 'figurant',
    threat_assessment: '1',
    bastion_clearance: '3',
    bloodtype: 'O',
  },
  {
    ICC_number: '9021 49000 1127',
    card_id: 'kadu-318',
    characterID: '415',
    character_name: 'Nila Qadir',
    douane_disposition: 'ACCESS GRANTED',
    faction: 'kadu',
    figu_accountID: '723',
    figu_name: 'Owen Koster',
    homeplanet: 'Kadu Reach',
    ic_birthday: '18-6-216NT',
    plotname: 'Medical transfer',
    rank: 'Pilot',
    status: 'figurant-recurring',
    threat_assessment: '2',
    bastion_clearance: '1',
    bloodtype: 'A',
  },
  {
    ICC_number: '7605 88091 6142',
    card_id: 'hasiru-073',
    characterID: '416',
    character_name: 'Sera Tal',
    douane_disposition: 'DECEASED',
    faction: 'hasiru',
    figu_accountID: '724',
    figu_name: 'Levi de Wit',
    homeplanet: 'Hasiru Garden',
    ic_birthday: '30-12-205NT',
    plotname: 'Archive anomaly',
    rank: 'Archivist',
    status: 'figurant',
    threat_assessment: '5',
    bastion_clearance: '4',
    bloodtype: 'B',
  },
  {
    ICC_number: '4441 23999 1200',
    card_id: 'sona-311',
    characterID: '417',
    character_name: 'Elias Mar',
    douane_disposition: 'ACCESS PENDING',
    faction: 'sona',
    figu_accountID: '',
    figu_name: '',
    homeplanet: 'Ghara',
    ic_birthday: '11-4-219NT',
    plotname: 'Unassigned extra row for sorting',
    rank: 'Courier',
    status: 'figurant',
    threat_assessment: '0',
    bastion_clearance: '0',
    bloodtype: 'AB',
  },
]

export const mockOcFigurantenNames = [
  { id: '719', name: 'Roos Schultheiss' },
  { id: '720', name: 'Sam Dekker' },
  { id: '721', name: 'Janne Smit' },
  { id: '722', name: 'Mara Visser' },
  { id: '723', name: 'Owen Koster' },
  { id: '724', name: 'Levi de Wit' },
]
